################################################################################
####  Genetic Algorithm
################################################################################


#######################################
####  Initialization
#######################################

#' Randonly Generate the Initial Generation
#'
#' @description Bernoulli sampling to form the initial generation of the 
#' Genetic Algorithm. The size of the initial generatino is set to be the
#' integer closest to 1.5C.
#'
#' @usage initialization(C)
#'
#' @param C chromosome length (number of predictor variables in the data)
#'
#' @details This function produces initial generation given the chromosome length
#' for Genetic Algorithm. The row of the generated boolean matrix represents the
#' locus of a gene(variable), and the column of the matrix represents different
#' members of the first generation(different models). The number of first
#' generation is defined to be integer closest to 1.5C.
#'
#' @value A C by 1.5C dimension Bolean Matrix with each column
#' representing a chromosome, where T marks that the gene (variable)
#' as active and F as inactive.
#'
#' @examples
#' initialization(10)

initialization <- function(C){
  
  # size of initial generation
  n <- as.integer(1.5 * C)
  
  # Bernoulli sampling T or F to obtain C of them 
  # A T in a locus of a gene (variable) means the perticular variable is included
  replicate(n, sample(c(F,T), size = C, replace = T))
}


#######################################
####  Parents Selection
#######################################

#' Select Parents Generated From \code{GA::initialization()}
#' Based on Given Fitness Function
#'
#' Selecting parents based on fitness ranks, with AIC as the
#' default fitness criteria. Alternatively, we can use tournament selection.
#'
#' @usage
#' selection(pop,f=AIC,dat)
#' selection(pop,f=BIC,dat)
#'
#' @param pop boleans matrix determined by \code{GA::initialization()}
#'
#' @param f fitness function that takes in an lm or glm model and returns a
#' a numerical 'qualification' of that model. Users can choose AIC or BIC or
#' even define by themselves. If the f argument is missing, the default is AIC.
#'
#' @param dat data frame containing the predictors in the model.
#' First column should be the response variable.
#'
#' @param model the linear model that user wants to use to fit in the data,
#' can be either \code{lm} or \code{glm}.
#'
#' @param ... additional arguments to pass to the model function.
#'
#' @details This function selects parents to breed by fitting linear regression
#' model to each possible parent generated by \code{GA::initialization()}
#' based on fitness rank with AIC as the default fitness function.
#'
#' @return Return a list, where containing chosen parents, fittest parent
#' and fitting score for each parent based on fitting function.
#'
#' @examples
#' dat <- mtcars # use the built-in mtcars data
#' C <- dim(dat)[2]-1 #Number of variables
#' pop <- initialization(C) #produce boleans matrix
#' selection(pop, f = AIC, dat)

selection <- function(pop, f, dat, model, ...){
  
  # number of chromosomes
  P <- ncol(pop)
  
  # Variables are columns of the dataset
  response <- colnames(dat)[1]
  predictors <- colnames(dat)[-1]
  
  # Input parameters must be named matrices
  stopifnot(!is.null(P) && !is.null(response) && !is.null(predictors))
  
  # Number of genes must equal number of predictors
  stopifnot(nrow(pop)==length(predictors))
  
  # Process each chromosome in parallel
  fit <- foreach::`%dopar%`(foreach::foreach(i = 1:P, .combine=c),{
    
    # Build a formula using the chosen predictors
    chosen <- pop[,i]
    
    # Account for situation when all predictors are F
    if(sum(chosen)){
      form <- as.formula(paste(response, "~",
                               paste(predictors[chosen], collapse = "+")))
      
      # Calculate the fitness using the provided fitness function
      f(model(formula=form,data=dat,...))
    }else{
      Inf
    }
  })
  
  # Compute a vector of probability weights
  # Since lowest fitness is the best, take the reverse rank
  fitness <- 2*rank(-fit)/(P*(P+1))
  
  # Sample from the P chromosomes, with weights specified in fitness,
  # with replacement, to generate a parenting population of size P.
  # Note there are duplicates within the parenting population.
  parent_ind <- sample(x = 1:P, size = P, replace = T, prob = fitness)
  parents <- pop[,parent_ind]
  #### This part is problemetic
  #### I was trying to use two methods to select parents
  #### The first method being using selection probabilities proportional to ranking
  #### to select both parents
  #### The second method being using selections probabilities proportional to ranking
  #### to select one parent and randonly select one parent
  #### And maybe we should implement the tournament selection?
  
  
  # Keep a copy of the fittest individual.
  fittest <- pop[,which.max(fitness)]
  
  # Build the selection result as a list
  sel.result <- list()
  sel.result$parents <- parents
  sel.result$fittest <- fittest
  sel.result$fit <- fit
  
  # Return the result
  sel.result
}


#######################################
####  Mutation
#######################################

#' Chromosome Mutation
#'
#' Make a chromosome with fixed probability 0.01 to mutate
#'
#' @usage mutation(chr)
#'
#' @param chr a logical vector representing an individual chromosome.
#'
#' @details This function makes a chromosome have a 1% fixed chance to mutate
#' in each locale. If mutation happens at one locale, it will make the value
#' in that locale from T to F(or F to T).
#'
#' @return Return a mutated chromosome vector
#' with the same length as input one.
#'
#' @examples
#' ind<-initialization(10)[,1]
#' mutation(ind)

mutation <- function(chr){
  
  # For each element of chr determine whether to mutate with 1% prob
  mutate <- sample(c(T,F), length(chr), prob = c(0.01,0.99), replace = T)
  
  # 'exclusive or' will toggle F to T and T to F
  xor(chr, mutate)
}

#######################################
####  Crossover
#######################################

#' Genetic Operatior: Chromosome Crossover and Mutation
#'
#' Make 2 individual parent chromosomes crossover and
#' mutate when breeding offsprings.
#'
#' @usage crossover(chr1,chr2)
#'
#' @param chr1,chr2 a numeric vectors represents individual parent chromosome.
#'
#' @details This function makes two individual parent chromosomes
#' perfrom crossover and mutation when breeding next generation.
#' Note that the crossover is simply one-point crossover
#' and the mutation is based on \code{GA::mutation()}.
#'
#' @return A matrix with each column representing the
#' offsprings from a process of crossover and mutation.
#'
#' @examples
#' ind1<-initialization(10)[,1]
#' ind2<-initialization(10)[,2]
#' crossover(ind1,ind2)

crossover <- function(chr1, chr2){
  
  C1 <- length(chr1)
  C2 <- length(chr2)
  
  # Make sure we're working with equal-sized vectors
  stopifnot(C1==C2)
  
  #randomly select a point as the point of crossover.
  k <- sample(1:(C1-1), 1)
  
  # Return the crossed chromosomes together
  cbind(
    mutation(c(chr1[1:k], chr2[(k+1):C1])),
    mutation(c(chr2[1:k], chr1[(k+1):C1]))
  )
}


#######################################
####  Choose Next Generation
#######################################





